### ISSUE TITLE
Memory limits in POD environment

### ISSUE THREAD

**Issue by eswarantg** [kahing/goofys#310]
Thanks for the great product.
We are using goofys to access S3.

A point to note is that we are running it in OperShift Container environment.
```
oc v1.5.1
kubernetes v1.5.2+43a9be4
```

The Host OS we are using is 
```
Linux xxxxxxxxx 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

The node characteristics that hosts the pod
```
Capacity:
 alpha.kubernetes.io/nvidia-gpu:	0
 cpu:					16
 memory:				31731548Ki
 pods:					160
Allocatable:
 alpha.kubernetes.io/nvidia-gpu:	0
 cpu:					16
 memory:				31731548Ki
 pods:					160
```
Note the node has 30.26 Gi of memory available.

The POD is limited to use 6 GB of memory
```
          resources:
            limits:
              cpu: "2"
              memory: 6Gi
            requests:
              cpu: "1"
              memory: 4Gi
```

Goofys i undrestand attempts to use 1/2 of the available memory for buffering.
In a linux box the /proc/meminfo file content is used for determining the POD memory available.

This file looks like reflects the actual node memory parameters than the actual POD limit.
I would like to understand if 
**a. Is there any Pod level configuration that can be used to update the /proc/meminfo file to reflect the pod level configuration 
b. If not, can we update the Goofys to use a different mechanism for determining the memory limit.**
